FROM ansible-runner

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IG1lZGlhd2lraS1hcGIKZGVzY3JpcHRpb246IE1lZGlhd2lraSBh\
cGIgaW1wbGVtZW50YXRpb24KYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAptZXRhZGF0\
YToKICBkZXBlbmRlbmNpZXM6IFsnZG9ja2VyLmlvL2Fuc2libGVwbGF5Ym9va2J1bmRsZS9tZWRp\
YXdpa2kxMjM6bGF0ZXN0J10KICBkaXNwbGF5TmFtZTogTWVkaWF3aWtpIChBUEIgR2FsYXh5KQpw\
bGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBBbiBBUEIgdGhhdCBkZXBs\
b3lzIE1lZGlhV2lraQogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6CiAgICAgIGRpc3BsYXlO\
YW1lOiBEZWZhdWx0CiAgICBwYXJhbWV0ZXJzOgogICAgICAtIG5hbWU6IG1lZGlhd2lraV9kYl9z\
Y2hlbWEKICAgICAgICBkZWZhdWx0OiBtZWRpYXdpa2kKICAgICAgICB0eXBlOiBzdHJpbmcKICAg\
ICAgICB0aXRsZTogTWVkaWF3aWtpIERCIFNjaGVtYQogICAgICAgIHBhdHRlcm46ICJeW2EtekEt\
Wl9dW2EtekEtWjAtOV9dKiQiCiAgICAgICAgcmVxdWlyZWQ6IFRydWUKICAgICAgLSBuYW1lOiBt\
ZWRpYXdpa2lfc2l0ZV9uYW1lCiAgICAgICAgZGVmYXVsdDogTWVkaWFXaWtpCiAgICAgICAgdHlw\
ZTogc3RyaW5nCiAgICAgICAgdGl0bGU6IE1lZGlhd2lraSBTaXRlIE5hbWUKICAgICAgICBwYXR0\
ZXJuOiAiXlthLXpBLVpdKyQiCiAgICAgICAgcmVxdWlyZWQ6IFRydWUKICAgICAgICB1cGRhdGFi\
bGU6IFRydWUKICAgICAgLSBuYW1lOiBtZWRpYXdpa2lfc2l0ZV9sYW5nCiAgICAgICAgZGVmYXVs\
dDogZW4KICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICB0aXRsZTogTWVkaWF3aWtpIFNpdGUg\
TGFuZ3VhZ2UKICAgICAgICBwYXR0ZXJuOiAiXlthLXpdezIsM30kIgogICAgICAgIHJlcXVpcmVk\
OiBUcnVlCiAgICAgIC0gbmFtZTogbWVkaWF3aWtpX2FkbWluX3VzZXIKICAgICAgICBkZWZhdWx0\
OiBhZG1pbgogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIHRpdGxlOiBNZWRpYXdpa2kgQWRt\
aW4gVXNlciAoQ2Fubm90IGJlIHRoZSBzYW1lIHZhbHVlIGFzIEFkbWluIFVzZXIgUGFzc3dvcmQp\
CiAgICAgICAgcmVxdWlyZWQ6IFRydWUKICAgICAgLSBuYW1lOiBtZWRpYXdpa2lfYWRtaW5fcGFz\
cwogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIHRpdGxlOiBNZWRpYXdpa2kgQWRtaW4gVXNl\
ciBQYXNzd29yZAogICAgICAgIHJlcXVpcmVkOiBUcnVlCiAgICAgICAgZGlzcGxheV90eXBlOiBw\
YXNzd29yZAo="

RUN git clone https://github.com/openshift/openshift-restclient-python
RUN cd openshift-restclient-python \
    && pip install -r requirements.txt \
    && python setup.py install

RUN echo "localhost ansible_connection=local" > /etc/ansible/hosts \
    && echo '[defaults]' > /etc/ansible/ansible.cfg \
    && echo 'library = /usr/share/ansible/openshift' >> /etc/ansible/ansible.cfg

ADD playbooks /runner/project/
COPY . /etc/ansible/roles/mediawiki-apb
ADD .kube /root/.kube
