---
# tasks file for mediawiki-apb
- name: DEBUG
  debug:
    msg: "{{ apb_action }}"
- include_role:
    name: dymurray.postgresql-apb
  vars:
    namespace: "{{ namespace }}"

- include_tasks: provision.yml
  when: apb_action == 'provision'
