---
# tasks file for mediawiki-apb
- name: DEBUG
  debug:
    msg: "{{ apb_action }}"

- include_tasks: provision.yml
  when: apb_action == 'provision'
- include_tasks: deprovision.yml
  when: apb_action == 'deprovision'

